### ISSUE TITLE
Store and retrieve gustaf mesh

### ISSUE THREAD

**Issue by CodeFloh** [tataratat/gustaf#22]
We have I/O operations for several file formats. But I think we don't have any utilities to store a mesh instance (Vertices, Edges, Faces or Volumes) to a file and retrieve it. I think this could be handy to have this in a standardized way. Would it be fine if I create something?

I imagine a dict structure that stores entries

- vertices
- volumes (or faces, edges, etc.)
- facegroup_* (for each face group, e.g., facegroup_inlet)
- vertexgroup_*

and the I/O happens through `np.savez` and `np.load`.

Storing groups could be made optional. Other options, such as using dictionaries for groups with `allow_pickle` could be possible.

**Comment by j042** [comment]
Since `numpy` is a strict dependency, I think using `np.savez` is a good start. A few month ago, I created a local branch for it and `gustaf/io/npz.py` file, but I see that I didn't finish it. As we expect some changes, I guess I won't even bother to push the WIP files.
Regarding `allow_pickle`, that'd be a strong no. A safer, but primitive, alternative would be joining nested keys with "_"
