### ISSUE TITLE
remove get_*(), some slots, and add saved properties helper.

### ISSUE THREAD

**Issue by j042** [tataratat/gustaf#31]
`get_<something>()` and extensive use of `__slots__` were experimental and I've been thinking about alternatives. I plan to add a helper that gives you the latest-saved array of `<something>`, instead of leaving it in slots. I know some classes/implementations depends on this, so I just wanted to open an issue as a heads up.

**Comment by j042** [comment]
@clemens-fricke @CodeFloh

**Comment by clemens-fricke** [comment]
Could you elaborate on what you want to replace these with? I think I currently only have dependencies on this inside of gustaf (see #30).  SbSOvRL does not depend on these slots. I think it would be best to not use the slots but either implement a setter and getter function (via decorators) or just implement these exclusively with get_<something>()

**Comment by j042** [comment]
`get_bounds()` will be replaced with `bounds()`. and if you wanna get the saved bounds from your latest compute, you can either get it by setting `return_saved=True` or through saved data manager, `.saved["bounds"]`. Probably will use setter and getter for main properties like vertices and connectivities, but not for anything else.

**Comment by CodeFloh** [comment]
1. Is `@cached_property` ab option at all? I don't fully understand, because some pages claim it actually uses cache memory, which we may not want.
2. I'm open to any solution, but I think as soon as such _derived quantities_ are stored, they need to be automatically invalidated when something like `vertices` is changed. So we'd need more expensive setters to achieve this. I would probably prefer keeping the mesh objects free of any derived quantities. We could give the getters that actually need to do some work a name that tells the user about it, e.g., `calculate_bounds` or `determine_bounds`. Algorithms that use these quantities should store them locally if they want to reuse them.

**Comment by CodeFloh** [comment]
3. We could create a read-only mesh subclass that stores `.flags.writeable = False` views of the vertex and connectivity arrays and stores all derived quantities indefinitely.
