### ISSUE TITLE
Nutils simplex mesh export

### ISSUE THREAD

**Issue by CodeFloh** [tataratat/gustaf#7]
The goal is to convert gustaf meshes (e.g. read from MIXD files) to the data structures required by Nutils for simplex meshes. Specifically, we need to create a dictionary that contains the arguments for the following function call (`nutils/mesh.py`):

```
def simplex(nodes, cnodes, coords, tags, btags, ptags, name='simplex', *, space='X')
```

Here, `nodes`, `cnodes`, `coords`, `tags`, `btags`, `ptags` are Numpy arrays.

Something like the following code should be possible in the end:

```
topo, geom = nutils.simplex(**to_nutils_simplex_mesh(gustaf_mesh))
```

Required tasks are, among others:

- [ ] Sort element node IDs
- [ ] Translate MIXD face/edge IDs to Nutils face/edge IDs

Only triangles and tetrahedra are required

Questions in this regard are:

- Where should this functionality be put? What file/folder?
- Does gustaf store some kind of face map, i.e., is there any way to associate face IDs (coming from MIXD) with element node IDs?

**Comment by j042** [comment]
Hey!


> * Where should this functionality be put? What file/folder?

you could create`gustaf/io/nutils.py` for this. Could you please also implement `load()` and `export()` methods that takes `mesh` and `fname` as args, just so that the format stays the same as `mixd`. If there's no official nutils mesh export format, maybe you can use [np.savez()](https://numpy.org/doc/stable/reference/generated/numpy.savez.html) for now?




> * Does gustaf store some kind of face map, i.e., is there any way to associate face IDs (coming from MIXD) with element node IDs?

Not explicitly, but you can always create "subelement-connectivity" array. For example. `Volumes.get_faces()`, `Faces.get_edges()`... subelement-index should match `mixd`'s numbering exactly.
